name: Run .bat Script

on:
  workflow_dispatch:

jobs:
  run-bat:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run .bat script
      run: |
        cd .minecraft
        run.bat
      shell: cmd
